### ISSUE TITLE
Feature request: include macrolanguages

### ISSUE THREAD

**Issue by sandbergja** [bbenno/languages#45]
### User story
As a developer, given an ISO-639-3 language code, I would like to find the name of its macrolanguage.

### Specific example

The [macrolanguages table](https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab) lists `zho` (Chinese) as a macrolanguage of `wuu` (Wu Chinese).

It would be very convenient if, using this gem, I could do something like the following:

```
Languages[:wuu]&.macrolanguage
=> #<Languages::Language:0x000000011a48c4c8 @iso639_3=:zho, @iso639_2b=:chi, @iso639_2t=:zho, @iso639_1=:zh, @scope=:macrolanguage, @type=:living, @name="Chinese">
```

### Source data

The macrolanguages table can be found at https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab.  The first column is the macrolanguage, the second column is the individual language.

**Comment by bbenno** [comment]
Done in 856b59326bdd44bbd4605f1d8df6f51751c9cb58.
I think we can publish v0.7.0 as soon as #44 is merged.
